package me.aitor.skywars.config;

import me.aitor.skywars.SkyWars;
import me.aitor.skywars.utils.Utils;
import com.google.common.collect.Lists;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class ConfigManager {
   public static SkyConfiguration main;
   public static SkyConfiguration score;
   public static SkyConfiguration abilities;
   public static SkyConfiguration shop;
   public static SkyConfiguration signs;

   public static void mainConfig() {
      File var0 = new File(SkyWars.getPlugin().getDataFolder(), "config.yml");
      main = new SkyConfiguration(var0);
      main.setHeader("-------------------------------- #", "", "SKYWARS", "By Aitor", "Lucha contra jugadores en el cielo", "", "-------------------------------- #");
      main.addDefault("check_updates", true, "Verificar si existe una nueva actualización (SE RECOMIENDA DEJARLO EN TRUE)");
      main.addDefault("debug", false, "Modo debug", "activar si ocurre algún fallo/error y necesitas enviarme (Aitor) el log del servidor");
      main.addDefault("debug-database", false, "Depurar base de datos (MySQL)", "activar si ocurre algún fallo/error y necesitas enviarme (Aitor) el log del servidor");
      main.addDefault("locale", "en", "Idiomas disponibles:", "      en: Inglés (Predeterminado)", "      es: Español", "      nl: Holandés");
      main.addDefault("kitmenu_rows", 3, "Filas/Lineas del Menú de Kits (ESPERANDO PARTIDA)");
      main.addDefault("kit_permission", false, "Si es verdadero, los jugadores con el permiso (skywars.kit.KitName) pueden comprar este kit");
      main.addDefault("maxtime", 1200, "Tiempo máximo para cada arena/partida");
      main.addDefault("spawn", "", "Coordenadas del lobby [MultiArena/Lobby]", "escribe /sw lobbyspawn para establecer el spawn del lobby");
      ArrayList var1 = new ArrayList();
      var1.add("Lobby");
      main.addDefault("lobbies_servers", var1, "Lista de servidores de lobby para tp aleatorio (SERVIDORES BUNGEECORD)");
      main.addDefault("max_items_types_chest", 15, "Máximo de ranuras utilizadas por cofre generado (EN PARTIDA)");
      main.addDefault("economy.mode", "Custom", "Tipos de economía:", "    Custom: incluida por defecto en SkyWars (ALTAMENTE RECOMENDADA)", "    Vault: se conecta con Vault y otros plugins como Essentials o iConomy", "    PlayerPoints: se conecta con PlayerPoints", "    Craftconomy3: se conecta con CraftConomy3", "    Coins: se conecta con Coins https://www.spigotmc.org/resources/48536/ (RECOMENDADA)");
      main.addDefault("economy.craftconomy3_currency", "Dollar", "Moneda configurada cuando se ha configurado CraftConomy3 (Predeterminado: Dollar)");
      main.addDefault("reward.death", 1, "recompensa que recibe cada sobreviviente cuando un jugador muere");
      main.addDefault("reward.kill", 2, "recompensa por matar a un jugador");
      main.addDefault("reward.win", 10, "recompensa para el ganador");
      main.addDefault("reward.wincmd.enabled", false, "Habilitar o deshabilitar los comandos para el ganador (EJECUTADOS POR LA CONSOLA)");
      ArrayList var2 = new ArrayList();
      var2.add("20/money give %winner% 20");
      var2.add("100/say %winner% won a game!");
      main.addDefault("reward.wincmd.list", var2, "Lista de comandos (VARIABLES: %winner% , %map%)", "\tFORMATO: 'CHANCE/CMD'", "\tEjemplo: 90/give %winner% minecraft:diamond_block 1", "\tCHANCE: 0-100");
      main.addDefault("item.kits", "1 PAPER", "Items en el lobby de espera, para mensaje y traducción ve a la sección de items en los archivos de mensajes", "Formato:   SLOT NOMBRE_DEL_ITEM", "SLOT De 1 a 9 (hotbar)", "Si deseas editar el ítem de la tienda en el Lobby, ve a shop.yml");
      main.addDefault("item.settings", "2 DIAMOND");
      main.addDefault("item.vote", "3 EMPTY_MAP");
      main.addDefault("item.exit", "9 BED");
      main.addDefault("menu.kits", (Object)null, "Opciones del menú de selección de kits");
      main.addDefault("menu.kits.unavailable.enabled", false, "Habilitar o deshabilitar si se debe reemplazar el icono de kit no disponible por algún ítem (Predeterminado: false)");
      main.addDefault("menu.kits.unavailable.item", "STAINED_GLASS_PANE:14", "ITEM_NAME:DATA");
      main.addDefault("mode.plugin", "MultiArena", "Modos del Plugin:", "      BungeeMode: Solo una partida por servidor (mejor rendimiento)", "      MultiArena: Partidas ilimitadas por servidor (desempeño inferior con muchas partidas)", "      Lobby: Solo sistema de Lobby para servidores Bungee (antes SkyWarsLobby)");
      main.addDefault("mode.bungee-autostart", true, "Inicio automático cuando una partida termina (BungeeMode)");
      main.addDefault("mode.bungeerandom", true, "Selecciona un mapa aleatorio de las arenas configuradas");
      main.addDefault("mode.bungeemapset", "default", "Selecciona siempre el mismo mapa (BUNGEERANDOM DEBE SER FALSE)");
      main.addDefault("server", "", "Configuración de BungeeMode para el Sistema de Signs (MySQL REQUERIDO)", "habilitado por defecto si el servidor está en BungeeMode, necesitarás un servidor de Lobby", "con SkyWars en modo Lobby para el Sistema de Signs (MySQL REQUERIDO EN AMBOS SERVIDORES)");
      main.addDefault("server.bungeeid", "SkyWars-1", "Nombre bungee que corresponde a este servidor (Solo para servidor de arena)");
      main.addDefault("data.type", "SQLite", "Tipos:", "    SQLite: Archivo local (Predeterminado)", "    MySQL: Se requiere servidor MySQL");
      main.addDefault("data.mysql.server", "localhost", "Dirección/IP del servidor MySQL");
      main.addDefault("data.mysql.db", "SkyWars", "nombre de la base de datos");
      main.addDefault("data.mysql.user", "root", "Usuario de MySQL");
      main.addDefault("data.mysql.port", 3306, "Puerto MySQL");
      main.addDefault("data.mysql.password", "password", "contraseña de MySQL");
      main.addDefault("data.mysql.tablename.data", "SkyWars_Data", "Nombre de la tabla de datos de jugadores");
      main.addDefault("data.mysql.tablename.economy", "SkyWars_Economy", "Nombre de la tabla de datos de economía personalizada");
      main.addDefault("data.mysql.tablename.servers", "SkyWars_Servers", "Nombre de la tabla de información de servidores");
      main.addDefault("options.weather", false, "habilitar o deshabilitar el clima en los mundos de arena");
      main.addDefault("options.creaturespawn", false, "habilitar o deshabilitar la aparición de mobs en los mundos de arena");
      main.addDefault("options.saveInventory", true, "guardar el inventario cuando el jugador entra a la partida y restaurarlo al salir");
      main.addDefault("options.forceLobbySpawn", true, "forzar teletransporte al spawn cuando un jugador entra");
      main.addDefault("options.orderedSpawnPoints", true, "puntos de spawn secuenciales en la arena");
      main.addDefault("options.disablePvP-Outside-The-Arena", false, "deshabilitar PvP en el mundo del Lobby");
      main.addDefault("options.disableDamage-Outside-The-Arena", false, "deshabilitar todo daño en el Lobby");
      main.addDefault("options.leaveMessage", false, "habilitar o deshabilitar el mensaje de salida cuando un jugador abandona el servidor");
      main.addDefault("options.joinMessage", false, "habilitar o deshabilitar el mensaje de entrada cuando un jugador se une al servidor");
      main.addDefault("options.disableLeaveItem", false, "deshabilitar el ítem de salida (cama)");
      main.addDefault("options.disablePerWorldTab", false, "deshabilitar la Tab separada por mundo (SE RECOMIENDA DEJARLO EN FALSE PARA SERVIDORES 1.8 & 1.9)");
      main.addDefault("options.disablePerWorldChat", false, "deshabilitar el chat separado por mundo");
      main.addDefault("options.disableSpectatorMode-Death", false, "deshabilitar el modo espectador cuando el jugador muere");
      main.addDefault("options.removeAllCageOnStart", true, "true: eliminar toda la jaula, false: eliminar solo el suelo de la jaula");
      main.addDefault("options.perWorldTabBypass", false, "Habilitar o deshabilitar la Tab por mundo para jugadores con el permiso: skywars.tab.bypass");
      main.addDefault("options.combatLogTime", 3, "El tiempo en segundos que CombatLog actuará después de que un jugador reciba daño de otro", "Predeterminado: 3");
      ArrayList var3 = new ArrayList();
      var3.add("help");
      var3.add("spawn");
      var3.add("home");
      main.addDefault("block.commands.mode", "blacklist", "Modos disponibles:", "      blacklist: bloquear todos los comandos en la lista", "      whitelist: solo permitir los comandos en la lista");
      main.addDefault("block.commands.ingame", var3, "Comandos bloqueados para jugadores en partida (en arena)");
      main.options().copyDefaults(true);
      main.getEConfig().setNewLinePerKey(true);
      main.save();
   }

   public static void scoreboardConfig() {
      File var0 = new File(SkyWars.getPlugin().getDataFolder(), "scoreboard.yml");
      score = new SkyConfiguration(var0);
      score.setHeader("VARIABLES:", "    - Nombre del jugador:         " + "%PLAYER%, %USERNAME%".toLowerCase(), "    - Monedas del jugador:        " + "%COINS%, %POINTS%".toLowerCase(), "    - Muertes del jugador:       " + "%SW-DEATHS%, %SW-D%, %STATS-DEATHS%".toLowerCase(), "    - Asesinatos del jugador:        " + "%SW-KILLS%, %SW-K%, %STATS-KILLS%".toLowerCase(), "    - Victorias del jugador:         " + "%SW-WINS%, %SW-W%, %STATS-WINS%".toLowerCase(), "    - Partidas jugadas:        " + "%SW-PLAYED%, %SW-P%, %STATS-PLAYED%".toLowerCase(), "    - Flechas disparadas:          " + "%SW-ARROW-SHOT%, %SW-AS%, %STATS-ARROW-SHOT%".toLowerCase(), "    - Flechas acertadas:           " + "%SW-ARROW-HIT%, %SW-AH%, %STATS-ARROW-HIT%".toLowerCase(), "    - Bloques rotos:       " + "%SW-BLOCKS-BROKEN%, %SW-BB%, %STATS-BLOCKS-BROKEN%".toLowerCase(), "    - Bloques colocados:        " + "%SW-BLOCKS-PLACED%, %SW-BP%, %STATS-BLOCKS-PLACED%".toLowerCase(), "    - Distancia recorrida:     " + "%SW-DISTANCE-WALKED%, %SW-DW%, %STATS-DISTANCE-WALKED%".toLowerCase(), "    - Tiempo jugado:         " + "%SW-TIME-PLAYED%, %SW-TP%, %STATS-TIME-PLAYED%".toLowerCase(), "    - Ratio de asesinatos/muertes:    " + "%SW-KILLS-DEATHS%, %SW-KDR%".toLowerCase(), "    - Vidrio seleccionado:      " + "%GLASS%".toLowerCase(), "VARIABLES DEL SCOREBOARD:", "    - Línea vacía:          %empty%", "VARIABLES DEL SCOREBOARD DE PARTIDA:", "    - Nombre de la arena:          " + "%ARENA-NAME%, %A-NAME%".toLowerCase(), "    - Máximo de jugadores en la arena:   " + "%ARENA-MAX-PLAYERS%, %A-MAX-P%".toLowerCase(), "    - Jugadores en la arena:    " + "%ARENA-INGAME-PLAYERS%, %A-INGAME-P%".toLowerCase(), "    - Título del evento actual: " + "%ARENA-EVENT-TITLE% %A-EVENT-TITLE%".toLowerCase(), "    - Tiempo del evento actual:  " + "%ARENA-EVENT-TIME% %A-EVENT-TIME%".toLowerCase(), "    - Racha actual: " + "%SW-KILL-STREAK% %SW-KS%".toLowerCase(), "CONDICIONALES DEL SCOREBOARD:", "    <a-events> Verifica si la arena tiene eventos habilitados", "    <a-ingame> Verifica si la arena está en partida");
      score.addDefault("lobby.enabled", true, "Habilitar o deshabilitar el Scoreboard del Lobby");
      ArrayList var1 = new ArrayList();
      var1.add("test1");
      var1.add("test2");
      score.addDefault("lobby.disabledWorlds", var1, "Lista negra del Scoreboard del Lobby (mundos deshabilitados)");
      score.addDefault("lobby.title", "&e&lSkyWars", "Título del Scoreboard del Lobby");
      ArrayList var2 = new ArrayList();
      var2.add("&5Monedas:");
      var2.add("&a%coins%");
      var2.add("%empty%");
      var2.add("&6Nombre del Servidor");
      score.addDefault("lobby.lines", var2, "Líneas del Scoreboard del Lobby (Máximo: 16)");
      score.addDefault("game.title", "&e&lSkyWars", "Título del Scoreboard de Partida");
      ArrayList var3 = new ArrayList();
      var3.add("<a-ingame><a-events>&5%a-event-title% en:");
      var3.add("<a-ingame><a-events>&a%a-event-time%");
      var3.add("<a-ingame><a-events>%empty%");
      var3.add("&5Mapa:");
      var3.add("&a%a-name%");
      var3.add("%empty%");
      var3.add("&5Jugadores:");
      var3.add("&a%a-ingame-p%/%a-max-p%");
      var3.add("%empty%");
      var3.add("&6Nombre del Servidor");
      score.addDefault("game.lines", var3, "Líneas del Scoreboard de Partida (Máximo: 16)");
      ArrayList var4 = new ArrayList();
      score.addDefault("hologram.locations", var4, "Coordenadas de hologramas");
      ArrayList var5 = new ArrayList();
      var5.add("&a%PLAYER%'s &7&k&l||&3&lSkyWars&7&k&l||I&aestadísticas");
      var5.add("&aVictorias&7: &6%sw-w%");
      var5.add("&aAsesinatos&7: &6%sw-k%");
      var5.add("&aMuertes&7: &6%sw-d%");
      var5.add("&aPartidas jugadas&7: &6%sw-p%");
      var5.add("&aFlechas disparadas&7: &6%sw-as%");
      var5.add("&aFlechas acertadas&7: &6%sw-ah%");
      var5.add("&aBloques rotos&7: &6%sw-bb%");
      var5.add("&aBloques colocados&7: &6%sw-bp%");
      var5.add("&aDistancia recorrida&7: &6%sw-dw%");
      var5.add("&aTiempo jugado&7: &6%sw-tp%");
      score.addDefault("hologram.lines", var5, "Líneas de hologramas");
      score.options().copyDefaults(true);
      score.getEConfig().setNewLinePerKey(true);
      score.save();
   }

   public static void abilitiesConfig() {
      File var0 = new File(SkyWars.getPlugin().getDataFolder(), "abilities.yml");
      abilities = new SkyConfiguration(var0);
      ArrayList var2 = new ArrayList();
      abilities.addDefault("enabled", true, "habilitar o deshabilitar las habilidades en el servidor");
      abilities.addDefault("configVersion", 2, "No edites este valor");
      abilities.addDefault("menu.lore.price", "&6Precio: %price% puntos");
      abilities.addDefault("menu.lore.disabled", "&8&lDESHABILITADO");
      abilities.addDefault("menu.lore.clickto.enable", "&6Haz clic para habilitar", "Haz clic en el icono de la habilidad para habilitar");
      abilities.addDefault("menu.lore.clickto.disable", "&6Haz clic para deshabilitar", "Haz clic en el icono de la habilidad para deshabilitar");
      abilities.addDefault("menu.lore.status.purchase", "&6Haz clic para comprar esta mejora de habilidad!", "Leyenda del ítem de nivel");
      abilities.addDefault("menu.lore.status.afford", "&c¡No puedes costear esta habilidad!");
      abilities.addDefault("menu.lore.status.purchased", "&c¡Ya comprada!");
      abilities.addDefault("menu.lore.status.unavailable", "&c¡Aún no puedes comprar este ítem!");
      abilities.addDefault("menu.lore.status.disabled", "&6Haz clic en el icono de la izquierda para habilitar");
      abilities.addDefault("menu.item.status.purchase", "95:4,1", "ítem mostrado en el menú ID:DATA,AMOUNT");
      abilities.addDefault("menu.item.status.afford", "95:14,1", "ítem mostrado en el menú ID:DATA,AMOUNT");
      abilities.addDefault("menu.item.status.purchased", "95:5,1", "ítem mostrado en el menú ID:DATA,AMOUNT");
      abilities.addDefault("menu.item.status.unavailable", "95:14,1", "ítem mostrado en el menú ID:DATA,AMOUNT");
      abilities.addDefault("menu.item.status.disabled", "95:8,1", "ítem mostrado en el menú ID:DATA,AMOUNT");
      abilities.addDefault("menu.item.level", "nivel %number%", "Nivel del ítem/habilidad");
      var2.add("%level-desc%");
      var2.add("");
      var2.add("%price-format%");
      var2.add("");
      var2.add("%status-format%");
      abilities.addDefault("menu.lore.levels.enabled", var2, "Formato de ítem para nivel habilitado");
      ArrayList var3 = new ArrayList();
      var3.add("%level-desc%");
      var3.add("");
      var3.add("%disabled%");
      var3.add("%status-format%");
      abilities.addDefault("menu.lore.levels.disabled", var3, "Formato de ítem para nivel deshabilitado");
      String var1 = "triple_arrow";
      ArrayList var4 = new ArrayList();
      var4.add("&7Dispara 3 flechas al mismo tiempo");
      addAbilitieSection(abilities, var4, var1, "&aDisparo triple de flechas", "262,3");
      ArrayList var5 = new ArrayList();
      var5.add("&7Tienes un %chance%% de disparar 3 flechas");
      var5.add("&7al mismo tiempo");
      addAbilitieLevelSection(abilities, var5, var1, "1", 50, 4, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "2", 100, 6, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "3", 200, 8, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "4", 1000, 10, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "5", 2000, 12, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "6", 5000, 14, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "7", 10000, 16, false, 3);
      addAbilitieLevelSection(abilities, var5, var1, "8", 20000, 18, false, 3);
      var1 = "adrenaline_boost";
      ArrayList var6 = new ArrayList();
      var6.add("&7Cuando te hieras, tienes la posibilidad de obtener un aumento de velocidad");
      addAbilitieSection(abilities, var6, var1, "&aImpulso de adrenalina", "373,1");
      ArrayList var7 = new ArrayList();
      var7.add("&7Tienes un %chance%% de obtener un aumento de velocidad");
      var7.add("&7cuando te hieras");
      addAbilitieLevelSection(abilities, var7, var1, "1", 50, 4, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "2", 100, 6, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "3", 200, 8, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "4", 1000, 10, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "5", 2000, 12, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "6", 5000, 14, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "7", 10000, 16, false, 0);
      addAbilitieLevelSection(abilities, var7, var1, "8", 20000, 18, false, 0);
      var1 = "feather_weight";
      ArrayList var8 = new ArrayList();
      var8.add("&7Recibe menos daño por caídas");
      addAbilitieSection(abilities, var8, var1, "&aPeso de pluma", "288,1");
      ArrayList var9 = new ArrayList();
      var9.add("&7Recibe un %value%% menos de daño por caídas en un %chance%% de las veces");
      addAbilitieLevelSection(abilities, var9, var1, "1", 50, 4, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "2", 100, 8, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "3", 200, 12, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "4", 1000, 16, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "5", 2000, 20, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "6", 5000, 24, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "7", 10000, 28, true, 50);
      addAbilitieLevelSection(abilities, var9, var1, "8", 20000, 32, true, 50);
      var1 = "aggressive_mode";
      ArrayList var10 = new ArrayList();
      var10.add("&7Inflige más daño cuando tienes menos");
      var10.add("&7de 5 corazones");
      addAbilitieSection(abilities, var10, var1, "&aModo agresivo", "267,1");
      ArrayList var11 = new ArrayList();
      var11.add("&7Cuando tienes menos de 5 corazones, infliges un %value%% más de daño en un %chance%% de las veces");
      addAbilitieLevelSection(abilities, var11, var1, "1", 50, 2, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "2", 100, 4, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "3", 200, 6, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "4", 1000, 8, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "5", 2000, 10, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "6", 5000, 12, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "7", 10000, 14, true, 50);
      addAbilitieLevelSection(abilities, var11, var1, "8", 20000, 16, true, 50);
      var1 = "arrow_tank";
      ArrayList var12 = new ArrayList();
      var12.add("&7Recibe menos daño de las flechas");
      addAbilitieSection(abilities, var12, var1, "&aBlindaje Antiproyectil", "307,1");
      ArrayList var13 = new ArrayList();
      var13.add("&7Tienes un %chance%% de recibir un %value%%");
      var13.add("&7menos daño por proyectiles");
      addAbilitieLevelSection(abilities, var13, var1, "1", 50, 4, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "2", 100, 6, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "3", 200, 8, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "4", 1000, 10, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "5", 2000, 12, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "6", 5000, 14, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "7", 10000, 16, true, 50);
      addAbilitieLevelSection(abilities, var13, var1, "8", 20000, 18, true, 50);
      var1 = "mining_luck";
      ArrayList var14 = new ArrayList();
      var14.add("&7La habilidad de minería se incrementa para que puedas obtener");
      var14.add("&7más de cada mineral");
      addAbilitieSection(abilities, var14, var1, "&aSuerte en la minería", "278,1");
      ArrayList var15 = new ArrayList();
      var15.add("&7Tienes un %chance%% de obtener %value% de un");
      var15.add("&7recurso al minar un mineral");
      addAbilitieLevelSection(abilities, var15, var1, "1", 25, 4, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "2", 50, 8, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "3", 100, 12, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "4", 500, 16, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "5", 1000, 20, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "6", 2500, 24, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "7", 5000, 28, true, 2);
      addAbilitieLevelSection(abilities, var15, var1, "8", 10000, 32, true, 2);
      var1 = "woodchopping_luck";
      ArrayList var16 = new ArrayList();
      var16.add("&7La habilidad de tala se incrementa para que puedas obtener");
      var16.add("&7más de un tronco de una sola pieza");
      addAbilitieSection(abilities, var16, var1, "&aFortuna en la tala", "279,1");
      ArrayList var17 = new ArrayList();
      var17.add("&7Tienes un %chance%% de obtener %value% troncos");
      addAbilitieLevelSection(abilities, var17, var1, "1", 25, 4, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "2", 50, 8, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "3", 100, 12, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "4", 500, 16, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "5", 1000, 20, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "6", 2500, 24, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "7", 5000, 28, true, 2);
      addAbilitieLevelSection(abilities, var17, var1, "8", 10000, 32, true, 2);
      var1 = "pirate";
      ArrayList var18 = new ArrayList();
      var18.add("&7Encuentra tesoros ocultos en la tierra");
      addAbilitieSection(abilities, var18, var1, "&aPirata", "3,1");
      ArrayList var19 = new ArrayList();
      var19.add("1 1 apple");
      var19.add("2 12 arrow");
      var19.add("2 2 egg");
      var19.add("1 1 stone_sword");
      var19.add("2 6 wood");
      var19.add("2 6 cobblestone");
      var19.add("3 6 snow_ball");
      var19.add("1 1 leather_boots");
      abilities.addDefault("abilities." + var1 + ".treasures", var19, "Possible treasure items", "Format: MIN-AMOUNT MAX-AMOUNT ITEM:DATA");
      ArrayList var20 = new ArrayList();
      var20.add("&7Encuentra tesoro en %chance%% de la tierra");
      addAbilitieLevelSection(abilities, var20, var1, "1", 25, 4, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "2", 50, 6, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "3", 100, 8, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "4", 500, 10, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "5", 1000, 12, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "6", 2500, 14, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "7", 5000, 16, false, 0);
      addAbilitieLevelSection(abilities, var20, var1, "8", 10000, 18, false, 0);
      var1 = "fire_resistance";
      ArrayList var21 = new ArrayList();
      var21.add("&7Recibe menos daño por fuego");
      addAbilitieSection(abilities, var21, var1, "&aResistencia al fuego", "259,1");
      ArrayList var22 = new ArrayList();
      var22.add("&7Recibe un %value%% menos de daño por fuego y lava");
      var22.add("&7en un %chance%% de las veces");
      addAbilitieLevelSection(abilities, var22, var1, "1", 50, 4, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "2", 100, 8, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "3", 200, 12, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "4", 1000, 16, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "5", 2000, 20, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "6", 5000, 24, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "7", 10000, 28, true, 50);
      addAbilitieLevelSection(abilities, var22, var1, "8", 20000, 32, true, 50);
      abilities.options().copyDefaults(true);
      abilities.getEConfig().setNewLinePerKey(false);
      abilities.save();
   }

   private static void addAbilitieSection(SkyConfiguration var0, List<String> var1, String var2, String var3, String var4) {
      var0.addDefault("abilities." + var2 + ".enabled", true, "habilitar o deshabilitar esta habilidad");
      var0.addDefault("abilities." + var2 + ".name", var3, "título/nombre de la habilidad");
      var0.addDefault("abilities." + var2 + ".desc", var1, "descripción de la habilidad");
      var0.addDefault("abilities." + var2 + ".item", var4, "ítem mostrado en el menú ID:DATA,AMOUNT");
   }

   private static void addAbilitieLevelSection(SkyConfiguration var0, List<String> var1, String var2, String var3, int var4, int var5, boolean var6, int var7) {
      var0.addDefault("abilities." + var2 + ".levels_desc", var1, "descripción de niveles mostrada en el menú");
      var0.addDefault("abilities." + var2 + ".level." + var3 + ".price", var4, "precio del nivel");
      var0.addDefault("abilities." + var2 + ".level." + var3 + ".chance", var5, "probabilidad del nivel");
      if (var6) {
         var0.addDefault("abilities." + var2 + ".level." + var3 + ".value", var7, "valor del nivel");
      }

   }

   public static void shopConfig() {
      File var0 = new File(SkyWars.getPlugin().getDataFolder(), "shop.yml");
      shop = new SkyConfiguration(var0);
      if (!shop.isSet("config_version") || shop.getInt("config_version") != 1 && shop.getInt("config_version") != 2) {
         shop.setHeader("---------------------------------------------------------------- #", "", "IMPORTANTE: TODOS LOS NOMBRES DE MENÚ (SUBMENÚS Y MENÚ PRINCIPAL) DEBEN SER DIFERENTES", "", "---------------------------------------------------------------- #");
         ArrayList var1 = new ArrayList();
         shop.addDefault("config_version", 2, "No edites este valor");
         shop.addDefault("shopingame", true);
         shop.addDefault("item.enabled", false, "false (Menú de tienda e ítem deshabilitados), true (Menú de tienda e ítem habilitados)");
         shop.addDefault("item.inventorySlot", 1, "Ranura en la que se colocará el ítem (Recomendado: 0-8)");
         shop.addDefault("item.item", 340, "ID:Data o NOMBRE:Data (Si Data es 0, no es necesario escribirlo)");
         shop.addDefault("item.name", "&e&lShop", "Nombre del ítem");
         var1.add("&7Haz clic para abrir la tienda");
         var1.add("&7para comprar muchas cosas geniales para SkyWars");
         shop.addDefault("item.lore", var1, "lore: Leyenda o descripción del ítem");
         shop.addDefault("shop_size", 6, "Tamaño total del menú de la tienda (filas) (VALOR MÁXIMO: 6)");
         shop.addDefault("main.main_name", "&fTienda de SkyWars", "main_name: Título del menú principal");
         shop.addDefault("main.items.51.item", 340, "ítem: ID:Data o NOMBRE:Data");
         shop.addDefault("main.items.51.name", "&9Cerrar menú", "nombre: Nombre del ítem");
         ArrayList var2 = new ArrayList();
         var2.add("&7Cerrar la compra");
         var2.add("&7menú.");
         shop.addDefault("main.items.51.lore", var2, "Leyenda o descripción del ítem");
         shop.addDefault("main.items.51.action", "CLOSE", "acción:", "\tCLOSE: Cierra el menú", "\tNONE: No hace nada");
         shop.addDefault("all.49.item", 395, "ID:Data o NOMBRE:Data");
         shop.addDefault("all.49.name", "&6Puntos totales: &a%coins%", "nombre: Nombre del ítem");
         ArrayList var3 = new ArrayList();
         var3.add("&5Gana puntos por");
         var3.add("&5jugar partidas");
         shop.addDefault("all.49.lore", var3, "Leyenda o descripción del ítem");
         shop.addDefault("all.49.action", "CLOSE", "acción:", "\tCLOSE: Cierra el menú", "\tNONE: No hace nada");
         shop.addDefault("allsubmenus.50.item", 340, "ID:Data o NOMBRE:Data");
         shop.addDefault("allsubmenus.50.name", "&9Volver", "nombre: Nombre del ítem");
         ArrayList var4 = new ArrayList();
         var4.add("&7Regresa al menú de la tienda");
         shop.addDefault("allsubmenus.50.lore", var4, "Leyenda o descripción del ítem");
         shop.addDefault("allsubmenus.50.action", "MAIN", "acción:", "\tCLOSE: Cierra el menú", "\tNONE: No hace nada", "\tMAIN: Volver al menú principal");
         byte var5 = 22;
         shop.addDefault("submenus." + var5 + ".sub_name", "&fKits de SkyWars", "Título del submenú");
         shop.addDefault("submenus." + var5 + ".item", 265, "ID:Data o NOMBRE:Data");
         shop.addDefault("submenus." + var5 + ".name", "&eSkyWars Kits", "nombre: Nombre del ítem");
         ArrayList var6 = new ArrayList();
         var6.add("&7Compra kits de SkyWars");
         shop.addDefault("submenus." + var5 + ".lore", var6, "Leyenda o descripción del ítem");
         shop.addDefault("submenus." + var5 + ".content.11.item", "KIT,Fisherman", "Variable de ítem: KIT,KitName (Obtiene ítem, nombre, descripción y precio del kit)");
         shop.addDefault("submenus." + var5 + ".content.12.item", "KIT,Lumberjack");
         shop.addDefault("submenus." + var5 + ".content.13.item", "KIT,Spiderman");
         shop.addDefault("submenus." + var5 + ".content.14.item", "KIT,Blacksmith");
         shop.addDefault("submenus." + var5 + ".content.15.item", "KIT,Digger");
         shop.addDefault("submenus." + var5 + ".content.16.item", "KIT,Redstone_master");
         shop.addDefault("submenus." + var5 + ".content.17.item", "KIT,Farmer");
         shop.addDefault("submenus." + var5 + ".content.20.item", "KIT,Chicken");
         shop.addDefault("submenus." + var5 + ".content.21.item", "KIT,Joker");
         shop.addDefault("submenus." + var5 + ".content.22.item", "KIT,Scout");
         shop.addDefault("submenus." + var5 + ".content.23.item", "KIT,Pyromaniac");
         shop.addDefault("submenus." + var5 + ".content.24.item", "KIT,Archer");
         shop.addDefault("submenus." + var5 + ".content.25.item", "KIT,Enchanter");
         shop.addDefault("submenus." + var5 + ".content.26.item", "KIT,Enderman");
         shop.addDefault("submenus." + var5 + ".content.30.item", "KIT,Iron_golem");
         shop.addDefault("submenus." + var5 + ".content.31.item", "KIT,Healer");
         shop.addDefault("submenus." + var5 + ".content.32.item", "KIT,Bomber");
         shop.addDefault("submenus." + var5 + ".content.33.item", "KIT,Swordsman");
         shop.addDefault("submenu.abilities.enabled", true, "Habilitar o deshabilitar las habilidades en el menú de la tienda");
         shop.addDefault("submenu.abilities.name", "&fHabilidades de SkyWars - Page %number%", "Nombre del submenú de habilidades");
         shop.addDefault("submenu.abilities.slot", 24, "Ranura del ítem principal de habilidades");
         shop.addDefault("submenu.abilities.item.name", "&eHabilidades de SkyWars", "nombre del ítem de habilidades");
         shop.addDefault("submenu.abilities.item.item", 301, "ítem de habilidades");
         ArrayList var7 = new ArrayList();
         var7.add("&7Compra habilidades de SkyWars");
         shop.addDefault("submenu.abilities.item.lore", var7, "Descripción del ítem de habilidades");
         shop.addDefault("submenu.abilities.next.item", 338, "ítem de página siguiente de habilidades");
         shop.addDefault("submenu.abilities.next.name", "&6Página siguiente", "nombre del ítem de página siguiente de habilidades");
         shop.addDefault("submenu.abilities.next.slot", 54, "Ranura del ítem de página siguiente de habilidades");
         shop.addDefault("submenu.abilities.previous.item", 338, "ítem de página anterior de habilidades");
         shop.addDefault("submenu.abilities.previous.name", "&6Página anterior", "nombre del ítem de página anterior de habilidades");
         shop.addDefault("submenu.abilities.previous.slot", 46, "Ranura del ítem de página anterior de habilidades");
         shop.options().copyDefaults(true);
         shop.getEConfig().setNewLinePerKey(true);
         shop.save();
      }
   }

   public static void signsConfig() {
      File var0 = new File(SkyWars.getPlugin().getDataFolder(), "signs.yml");
      signs = new SkyConfiguration(var0);
      signs.setHeader("CONFIGURACIÓN DE SIGNOS");
      signs.addDefault("rotation", false, "Habilitar o deshabilitar el sistema de rotación (deshabilitado por defecto)", "Si la rotación está habilitada, el cartel seleccionará una arena aleatoria disponible, lo que significa que tu servidor puede tener 30 arenas y solo 10 carteles", "y todas las arenas podrán jugarse sin tener un cartel por cada arena");
      signs.addDefault("rotationDelay", 60, "Retraso en ticks (20 Ticks = 1 Segundo) cuando el cartel buscará otra partida después de estar en juego (Solo si la rotación está habilitada)");
      signs.addDefault("change_block", true, "Habilitar o deshabilitar el cambio del bloque según el estado de la arena");
      ArrayList var1 = Lists.newArrayList(new String[]{"&lSkyWars", "%state%", "&nMapa: %map%", "&8%players%/%maxplayers%"});
      signs.addDefault("format.game", var1);
      ArrayList var2 = Lists.newArrayList(new String[]{"&l----------", "BUSCANDO", "PARTIDAS", "&l----------"});
      signs.addDefault("format.searching", var2);
      signs.addDefault("state", "", "El bloque que se colocará en la pared según el estado de la arena (change_block debe estar habilitado)", "Formato del bloque: ITEM_NAME:DATA (Si DATA es 0, no es necesario escribirlo)");
      signs.addDefault("state.waiting", "STAINED_GLASS:5");
      signs.addDefault("state.starting", "STAINED_GLASS:4");
      signs.addDefault("state.full", "STAINED_GLASS:10");
      signs.addDefault("state.ingame", "STAINED_GLASS:14");
      signs.addDefault("state.searching", "STAINED_GLASS");
      signs.addDefault("signs", new ArrayList());
      signs.options().copyDefaults(true);
      signs.getEConfig().setNewLinePerKey(true);
      Iterator var3 = signs.getConfigurationSection("state").getKeys(false).iterator();

      while(var3.hasNext()) {
         String var4 = (String)var3.next();
         String var5 = signs.getString("state." + var4);
         signs.set("state." + var4, Utils.readItem(var5).toString());
      }

      signs.save();
   }
}
